port: 4000
host: localhost
safe: false

# Site settings
title: El Centro - Easy Jekyll Coming Soon Theme
email: elcentro@elcentro.com
description: > # this means to ignore newlines until "baseurl:"
  A theme designed to produce a simple coming soon page in a matter of minutes, saving you lots of time and effort in the process.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lukepatrick
github_username:  lukechanning

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

###Add Bourbon
gems: [bourbon, neat]

###Fix Sass Directory
sass:
    sass_dir: _sass
    style: compressed
